#Config file for networkprobe
#example:
#cycletime:
#   60
#hosts:
#   - host1
#   - host2
#ports:
#   - 80
#   - 8080
#   - 2003
#graphitehost:
#   graphite.ft.com
#graphiteprefix:
#   networkprobe.dev
#
#This will cause the probe to listen on ports 80, 8080 & 2003
#It will attempt to connect to each host (host1, host2) on those
#ports
#
#It will wait 60 seconds between connection attempts
#
#It will attempt to push data to the graphite server named in
#graphitehost with the prefix
cycletime:
    60
hosts:
    - localhost 
    - dave
ports:
    - 2000
    - 3000
graphitehost:
    graphite.ft.com 
graphiteprefix:
    networks.networkprobe.dev

hostname:
    test
